# This workflow will install Go dependencies, run tests and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides

---
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      #- name: Check go mod
      #- run: |
      #-   go mod tidy
      #-   git diff --exit-code go.mod
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  tests-on-unix:
    needs: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Install etcd
        run: make etcd
      - name: Run tests
        run: make test
        continue-on-error: false
